# Generated by Django 5.1.6 on 2025-03-05 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('linkedin_profile', models.CharField(max_length=254)),
                ('x_profile', models.CharField(max_length=254)),
                ('instagram_profile', models.CharField(max_length=254)),
                ('needs_qr', models.BooleanField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marcketing_check', models.BooleanField()),
            ],
        ),
    ]
