# Generated by Django 5.1.6 on 2025-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='landline_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
