# Generated by Django 5.1.6 on 2025-03-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_businesscard_landline_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='category',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
