# Generated by Django 5.1.6 on 2025-03-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0003_businesscard_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscard',
            old_name='username',
            new_name='old_username',
        ),
    ]
