# Generated by Django 5.1.6 on 2025-03-09 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0004_rename_username_businesscard_old_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
