# Generated by Django 5.1.6 on 2025-03-09 17:04

from django.db import migrations
import uuid


def gen_username(apps, schema_editor):
    MyModel = apps.get_model("business_card", "BusinessCard")
    for row in MyModel.objects.all():
        row.username = uuid.uuid4()
        row.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0005_businesscard_username'),
    ]

    operations = [
        migrations.RunPython(gen_username, reverse_code=migrations.RunPython.noop),
    ]
