# Generated by Django 5.1.6 on 2025-03-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0007_alter_businesscard_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='old_username',
        ),
    ]
