# Generated by Django 5.1.6 on 2025-03-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0008_remove_businesscard_old_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
